body {
    background-color: black;
    color: white;
}

.title {
    color: white;
}

.logo img {
    filter: invert(1);
}

.description a {
    color: white;
}

---

title: Brent Parker 
Data Analyst                                             # your name (or website title) here
logo: "/images/Self Pic.jpg?raw=true"                    # your photo (or logo) here
description: >                                           # your text below (remove <br> elements if you don't need line breaks)
  Data Driven Analyst @ Vietmart | SQL | Excel | Python | Power BI 
  Data and process-driven analyst with nearly 3 years of experience. 
  <br><br>
  <a href="https://www.linkedin.com/in/brent-parker-73932421b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
